### ISSUE TITLE
RSS feed?

### ISSUE THREAD

**Issue by sangh** [chromakode/blog#1]
Not really an issue, but a feature request:  would it be possible to add an RSS feed to `chromakode.com`?

Thanks!

**Comment by kfdm** [comment]
It looks like the RSS feed was moved to https://chromakode.com/rss.xml at some point. Could also probably re-add the `<link>` tag. (ended up digging into the code a bit to find the feed url 😆 )

**Comment by chromakode** [comment]
Thanks for noting this @kfdm, and thanks for subscribing! :grin: I had copied the `head` component from astro's blog template, which I noticed was also mitting a discovery tag, so I opened a PR to add it: https://github.com/withastro/astro/pull/6382
