### ISSUE TITLE
RSS feed url broken

### ISSUE THREAD

**Issue by Ramblurr** [chromakode/blog#2]
Hi there! Love your blog. For awhile now I've had to read it outside my feed reader since the feed url 404s: https://chromakode.com/rss.xml

I discovered your blog had a github repo.. so here I am :)

Please close and ignore this if you're not interested in fixing it, I'm not trying to go around making unnecessary work for you. But if you intend to support an rss feed, well here's a bug report.

**Comment by chromakode** [comment]
Thank you very much for pointing this out! I had no idea it had broken.
Should be fixed now!

**Comment by Ramblurr** [comment]
Many thanks!
